"""
Django settings for guodongba project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import os.path 

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kz9rhg$mq+u%gs*lndnlr^3j5zxa7ubq4b+mjk-+9#s%dv=o!z'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
DEBUG = True 

ALLOWED_HOSTS = ['localhost','127.0.0.1','.182.61.8.185*','182.61.8.185','guodongs.com','.guodongs.com.','.guodongs.com','guodongs.com:8000','*.guodongs.com:*','*.guodongs.com']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'customer',
    'business',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'guodongba.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            os.path.join(BASE_DIR, 'customer/templates').replace('\\','/'), 
            os.path.join(BASE_DIR, 'business/templates').replace('\\','/'), 
            os.path.join(BASE_DIR, 'guodongba/templates').replace('\\','/'), 
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'guodongba.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'guodongba',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': '',
        'PORT': '',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-CN'

TIME_ZONE = 'UTC'

#USE_I18N = True

#USE_L10N = True

#USE_TZ = True

USE_I18N = False 

USE_L10N = False 

USE_TZ = False 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

SITE_ROOT = os.path.join(os.path.abspath(os.path.dirname(__file__)),'')
STATIC_ROOT = os.path.join(SITE_ROOT,'static')
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    ("css", os.path.join(STATIC_ROOT,'css')),
    ("demo", os.path.join(STATIC_ROOT,'demo')),
    ("fonts", os.path.join(STATIC_ROOT,'fonts')),
    ("font-awesome", os.path.join(STATIC_ROOT,'font-awesome')),
    ("img", os.path.join(STATIC_ROOT,'img')),
    ("js", os.path.join(STATIC_ROOT,'js')),
    ("images", os.path.join(STATIC_ROOT,'images')),
    ("admin_ajax", os.path.join(STATIC_ROOT,'admin_ajax')),
    ("admin_css", os.path.join(STATIC_ROOT,'admin_css')),
    ("admin_js", os.path.join(STATIC_ROOT,'admin_js')),
    ("admin_img", os.path.join(STATIC_ROOT,'admin_img')),
    ("admin_less", os.path.join(STATIC_ROOT,'admin_less')),
    ("admin_fonts", os.path.join(STATIC_ROOT,'admin_fonts')),
)

MEDIA_URL = '/images/' 
MEDIA_ROOT = os.path.join(SITE_ROOT,'images')

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/login_success/'